### ISSUE TITLE
Spark Not Working on Multidc nodes

### ISSUE THREAD

**Issue by MadDataScience** [DSPN/amazon-cloudformation-dse#36]
I've got a single multidc datacenter up and running. According to opscenter, spark is running on all the nodes. (I'd like to insert a friendly suggestion that you add a bit more on what to expect in the README.md. It's not totally clear what are all the events that need to complete before the cluster is ready to go.) Anyway, I ssh into one of the datacenter nodes and try running `dse spark` and get the following
```
ubuntu@ip-172-31-26-119:~$ dse spark
Exception in thread "main" java.io.IOException: Failed to open native connection to Cassandra at {54.167.239.32}:9042
	at com.datastax.spark.connector.cql.CassandraConnector$.com$datastax$spark$connector$cql$CassandraConnector$$createSession(CassandraConnector.scala:160)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$3.apply(CassandraConnector.scala:146)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$3.apply(CassandraConnector.scala:146)
	at com.datastax.spark.connector.cql.RefCountedCache.createNewValueAndKeys(RefCountedCache.scala:31)
	at com.datastax.spark.connector.cql.RefCountedCache.acquire(RefCountedCache.scala:56)
	at com.datastax.spark.connector.cql.CassandraConnector.openSession(CassandraConnector.scala:79)
	at com.datastax.spark.connector.cql.CassandraConnector.withSessionDo(CassandraConnector.scala:107)
	at org.apache.spark.deploy.SparkNodeConfiguration$.apply(SparkNodeConfiguration.scala:38)
	at org.apache.spark.deploy.SparkConfigurator.sparkNodeConfiguration$lzycompute(SparkConfigurator.scala:64)
	at org.apache.spark.deploy.SparkConfigurator.sparkNodeConfiguration(SparkConfigurator.scala:64)
	at org.apache.spark.deploy.SparkConfigurator.dseDriverProps$lzycompute(SparkConfigurator.scala:126)
	at org.apache.spark.deploy.SparkConfigurator.dseDriverProps(SparkConfigurator.scala:110)
	at org.apache.spark.deploy.SparkConfigurator.<init>(SparkConfigurator.scala:98)
	at org.apache.spark.deploy.DseSparkArgsPreprocessor.sparkConfigurator$lzycompute(DseSparkArgsPreprocessor.scala:62)
	at org.apache.spark.deploy.DseSparkArgsPreprocessor.sparkConfigurator(DseSparkArgsPreprocessor.scala:62)
	at org.apache.spark.deploy.DseSparkArgsPreprocessor.updatedArgs$lzycompute(DseSparkArgsPreprocessor.scala:70)
	at org.apache.spark.deploy.DseSparkArgsPreprocessor.updatedArgs(DseSparkArgsPreprocessor.scala:65)
	at org.apache.spark.deploy.DseSparkSubmitBootstrapper$.main(DseSparkSubmitBootstrapper.scala:25)
	at org.apache.spark.deploy.DseSparkSubmitBootstrapper.main(DseSparkSubmitBootstrapper.scala)
Caused by: com.datastax.driver.core.exceptions.AuthenticationException: Authentication error on host /54.167.239.32:9042: Host /54.167.239.32:9042 requires authentication, but no authenticator found in Cluster configuration
	at com.datastax.driver.core.AuthProvider$1.newAuthenticator(AuthProvider.java:40)
	at com.datastax.driver.core.Connection$5.apply(Connection.java:251)
	at com.datastax.driver.core.Connection$5.apply(Connection.java:235)
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:906)
	at com.google.common.util.concurrent.Futures$1$1.run(Futures.java:635)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
	at com.google.common.util.concurrent.Futures$1.run(Futures.java:632)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
	at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185)
	at com.datastax.driver.core.Connection$Future.onSet(Connection.java:1181)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1012)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:935)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:840)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:830)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:348)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)
```

As an aside, I'm also playing with the singledc deployment. I was going to try turning on Spark as per our discussion in #26 but on a lark I thought I'd try running `dse spark` there to see if it worked. To my surprise, it did, though I'm guessing the Cassandra connector is not there (haven't tried). I did notice, however, that it's on Spark 1.6.2. Is DSE just behind on this? Is this simple to upgrade?

**Comment by cpoczatek** [comment]
This is a combination of an unhelpful error and my fault for not updating the Readme. This is thrown because the templates now turn on password auth with the default user/pw cassandra/cassandra. Non-default pw will be exposed in the template soon. Either add auth, eg `dse -u cassandra -p cassandra...` or disable in LCM by going to `Config Profiles -> Default config -> cassandra.yaml -> authenticator = AllowAllAuthenticator`, save, and run a Config job on the cluster.

There is still an exception thrown when stating the spark shell (issue #37) However, the below 'hello w world' test ran when I tried.
```
dse hadoop fs -put FILE cfs:///user/ubuntu/FILE
# ^^^ at a prompt, vvv in spark shell
val lines = sc.textFile("FILE")
val words = lines.flatMap(_.split("\\s+"))
val wc = words.map(w => (w, 1)).reduceByKey(_ + _)
wc.saveAsTextFile("README.count")
```

As for versions, yes DSE's packaged Spark is usually a little behind for testing/stability reasons. I have no experience with updating to a non-packaged version of Spark, so I'm not really sure.
